### PR TITLE
Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by mthpower**

### CODE REVIEW

**Comment by lamby** [comment]
(Closed?)

**Comment by PeterJCLaw** [comment]
Yeah, to replace with a PR against your fork @lamby.

**Comment by mthpower** [comment]
Hi Chris, @PeterJCLaw informed me that we've switched to lamby/django-force-logout. Opening a PR there.

**Comment by lamby** [comment]
Ahhh didn't spot that. Cheers!

**Pull request closed without merging**
